# Define iOS platform version (required to avoid warnings)
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Enforce minimum iOS deployment target for all pods
    # Fixes: "The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 10.0"
    target.build_configurations.each do |config|
      # Set minimum deployment target to iOS 12.0 (minimum required) or 13.0 (to match platform)
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f
      if deployment_target < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      
      # Fix Swift optimization level warnings
      # Fixes: "Disabling previews because SWIFT_VERSION is set and SWIFT_OPTIMIZATION_LEVEL=-0, expected -Onone"
      if config.build_settings['SWIFT_VERSION']
        # For Debug builds, use -Onone (no optimization) to enable previews
        if config.name == 'Debug'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        # For Release builds, use -O (optimized) but ensure it's properly set
        elsif config.name == 'Release'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        end
      end
      
      # Suppress keyWindow deprecation warnings for third-party pods
      # This is a known issue with some Flutter plugins that haven't updated to iOS 13+ APIs
      config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_CFLAGS'] << '-Wno-deprecated-declarations'
      config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_SWIFT_FLAGS'] << '-Xcc -Wno-deprecated-declarations'
    end
  end
  
  # Also update the Pods project's deployment target
  installer.pods_project.build_configurations.each do |config|
    deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f
    if deployment_target < 12.0
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
