package com.compostkaki.shared.data.repository

import com.compostkaki.shared.data.createSupabaseClient
import com.compostkaki.shared.data.models.Bin
import io.github.jan.supabase.postgrest.postgrest
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Columns
import kotlinx.serialization.Serializable

@Serializable
data class CreateBinRequest(
    val name: String,
    val location: String? = null
)

class BinRepository {
    private val supabase = createSupabaseClient()
    
    suspend fun getBinsForUser(userId: String): Result<List<Bin>> {
        return try {
            // Get bins where user is a member
            val memberBins = supabase.from("bin_members")
                .select(columns = Columns.ALL) {
                    filter {
                        eq("user_id", userId)
                    }
                }
                .decodeList<BinMember>()
            
            val binIds = memberBins.map { it.bin_id }
            
            if (binIds.isEmpty()) {
                return Result.success(emptyList())
            }
            
            val bins = supabase.from("bins")
                .select(columns = Columns.ALL) {
                    filter {
                        `in`("id", binIds)
                    }
                }
                .decodeList<Bin>()
            
            Result.success(bins)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    suspend fun getBinById(binId: String): Result<Bin> {
        return try {
            val bin = supabase.from("bins")
                .select(columns = Columns.ALL) {
                    filter {
                        eq("id", binId)
                    }
                }
                .decodeSingle<Bin>()
            
            // Get contributors
            val contributors = supabase.from("bin_members")
                .select(columns = Columns.ALL) {
                    filter {
                        eq("bin_id", binId)
                    }
                }
                .decodeList<BinMember>()
            
            Result.success(
                bin.copy(
                    contributors_list = contributors.map { it.user_id }
                )
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    suspend fun createBin(name: String, userId: String): Result<Bin> {
        return try {
            val bin = supabase.from("bins")
                .insert(
                    Bin(
                        id = "", // Will be generated by DB
                        name = name,
                        location = name,
                        user_id = userId,
                        contributors = 1,
                        progress = 0,
                        health_status = "Healthy"
                    )
                ) {
                    select(columns = Columns.ALL)
                }
                .decodeSingle<Bin>()
            
            // Add user as member
            supabase.from("bin_members").insert(
                BinMember(
                    user_id = userId,
                    bin_id = bin.id,
                    role = "owner",
                    joined_at = kotlinx.datetime.Clock.System.now().toString()
                )
            )
            
            Result.success(bin)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    suspend fun joinBin(binId: String, userId: String): Result<Unit> {
        return try {
            // Check if already joined
            val existing = supabase.from("bin_members")
                .select(columns = Columns.ALL) {
                    filter {
                        eq("user_id", userId)
                        eq("bin_id", binId)
                    }
                }
                .decodeSingleOrNull<BinMember>()
            
            if (existing != null) {
                return Result.success(Unit)
            }
            
            supabase.from("bin_members").insert(
                BinMember(
                    user_id = userId,
                    bin_id = binId,
                    role = "member",
                    joined_at = kotlinx.datetime.Clock.System.now().toString()
                )
            )
            
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
    
    suspend fun updateBinHealth(binId: String, healthStatus: String): Result<Unit> {
        return try {
            supabase.from("bins")
                .update(mapOf("health_status" to healthStatus)) {
                    filter {
                        eq("id", binId)
                    }
                }
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}

@Serializable
data class BinMember(
    val user_id: String,
    val bin_id: String,
    val role: String,
    val joined_at: String
)

